travis:
  secure:
    BINSTAR_TOKEN: fqDCXTZN4KZ2zTguhTbn9iW9+ZkWAGYJ+lPnasgMXzmOJA4jBRxLchBYYmotLpFmMoi4WssG4stIbPINQHJVjyP0JPTOdrS2hgE74WBkabkG58u/s/qXV1PdyXR+nz2TcHaPGimWozjulokoxSP4ABKSOoeIMV0BsZZ+njEn5NF4P080Zzg0pSGvq3fuENySqT0WnVoC/NQ2Kv151c5TQxC0y8LQWOgtKinSaOYnFyy2Kaj2yEyA6xAGhoHqHqMRZC6j66WXruYc9HnfaNThM7WuQyuXNVzRXddxN3Eez0y60oIFld+ZDVxP9MtcQ3xTP7+6w4+g2N4ciTMnZOb8McSi4UNhJkdyLHD/O/yZkWKkJxFGNV0BgMTAGjCy4ASuT7rCdz4wVqwdzGzAtT2MUDGexeO28CDwn/cIc/3Mn0x7dwZ59symn+8ZqCwJY67z19Inh3ivAWnmE5+wTt+huiaibgPmXnrv3Hztmd980OJB9x4xUmyhJGIofpnRes+5+K2RQNAOeKw3DG0l3ruPV6/7QrWuNAukXdVQe3Ahl0LSgNWdLmjUmWHPwMb4COwK2JjUXgObktbur4zBj1/bGIgKGwZTuBUskrfpacmkxThUbU0E7iChZNHpplrVtRU72Quav0adJRMmFqNr3dWMthRmUeVxq4qRWKEVePzVxjo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
