travis:
  secure:
    BINSTAR_TOKEN: N7+k7SAYAMHMc3P/v4shxIlsu8BkiT/jl5xRi8WksDopKwI+Sg98e/RU8Rt1jbON/7fTgZJ4g4CwrEqWKtjyUN7ahsMDYquvk4aQei4qF//JnzsyGzyta0NEudROclL0DC2DFyedDBWOKEnvRho2qtYxIlhyyeCe8oFYCz8cvMbk4IUpkob5wvNfaSWrfZ6AAb/35Lxv6OLzPdo+XwGErz7EerSHfxkQ3StIO9E6y7o5BpMozM0QIBDPwPPKgW6Tq0KVnXBth9dvQxua5Yhrb6orb8aLA2saMSy4yK04LnwNWGW/LHnZgN1LcxSgVWpjXT9/sl64ILjfWhmDNwMZcF7i+XhfqsUy6dFYdSnxfNusuPkvgqp2LaIYk1BrrO5uXl+p9BChUL0pWj10dC7N3168/r1qH21XBziBrw5ph4IQwC+0eub4/1747S3cVvXiIwdKYGvW4SnypcJjKfQUE3OgFLXISIfdrV8MZuryBKj/xQDQO+8Tp1VLJ0VLHeLl1Xi2/+8qf05LmK7nVY34dSpXHT/C1MjSG14ovhsZFjsmkLP9ohAEo+HN3mMezNhxUC7z+XfquCI8z6yLLwApk15ESWE+TiAG8mGX+Np/5sL/L3crGPcozQPqVozgwvqdL264fZq5Jw9ijN/4Y5caL11DVaaW2SjPTedERY5HvJE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
